### PR TITLE
Feature: `/foo/` maps to `content/foo/index.md(x)`.

### PR DESCRIPTION
**Pull request by laosb**
Sorry for silently submitting a PR to add feature, but I feel this should be the default behavior people would expect out of box, so 🤷‍♂️.

I achieved this in my own project so I feel it might just be easier to submit this very simple feature via GitHub web interface.

### CODE REVIEW

**Comment by amiroff** [comment]
Thanks for contribution! Really cool convention, breaks the build though. Could you please re-check?

**Comment by amiroff** [comment]
Hey, @laosb 

I re-implemented the same feat with few more changes causing build to fail in `index_fallback` branch. Could you sync them to your PR so that we don't loose your contributor information?

Thanks!

**Comment by laosb** [comment]
Sorry for late reply, will do tonight.

**Comment by laosb** [comment]
Seems like build succeeded. I tried rebase but git just abandoned my commit in that way, so I did a merge. It seems like you converted existing page links, which should not break the build, or I missed something. Anyway, if an extra merge commit is not acceptable, maybe I can just integrate those changes manually.

**Comment by amiroff** [comment]
Thanks, merging!

**Pull request merged**
